sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '8'
- '10'
- '11'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.8'
  - node_js: '0.10'
  - node_js: '0.12'
  - node_js: '4'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: EslwH222OIkeH0UCKEJA7cjS5Jc5aoCmKecg83qBmR4hyAmPXm+EmWehtWaqE3JKQr/c1hs+pBAAlnmypHJ7rorC1WPZZeqcNRRZVV94E5XF+FLk5aYgkA9ZN1wG364oGiEdEwz3PkKRduqVrlXptWCY3NChr8xc5hczT4jEwlg=
